### ISSUE TITLE
caffe version

### ISSUE THREAD

**Issue by StarIsFalling** [tensor-yu/cascaded_mobilenet-v2#15]
Hi,thx for your job!
Can you provide your caffe version?Or which one you fork from?Mine is from weiliu.When I try to compile caffe after updating image_data_layer,there are several mistakes like follows:

src/caffe/layers/image_data_layer.cpp: In member function ‘virtual void caffe::ImageDataLayer<Dtype>::DataLayerSetUp(const std::vector<caffe::Blob<Dtype>*>&, const std::vector<caffe::Blob<Dtype>*>&)’:
src/caffe/layers/image_data_layer.cpp:74:41: error: ‘solver_rank’ is not a member of ‘caffe::Caffe’
     if (this->phase_ == TRAIN && Caffe::solver_rank() > 0 &&
                                         ^~~~~~~~~~~
src/caffe/layers/image_data_layer.cpp: In instantiation of ‘void caffe::ImageDataLayer<Dtype>::DataLayerSetUp(const std::vector<caffe::Blob<Dtype>*>&, const std::vector<caffe::Blob<Dtype>*>&) [with Dtype = float]’:
src/caffe/layers/image_data_layer.cpp:200:1:   required from here
src/caffe/layers/image_data_layer.cpp:101:39: error: request for member ‘size’ in ‘((caffe::ImageDataLayer<float>*)this)->caffe::ImageDataLayer<float>::<anonymous>.caffe::BasePrefetchingDataLayer<float>::prefetch_’, which is of non-class type ‘caffe::Batch<float> [3]’
   for (int i = 0; i < this->prefetch_.size(); ++i) {
                       ~~~~~~~~~~~~~~~~^~~~
src/caffe/layers/image_data_layer.cpp:102:5: error: base operand of ‘->’ has non-pointer type ‘caffe::Batch<float>’
     this->prefetch_[i]->data_.Reshape(top_shape);
     ^~~~
src/caffe/layers/image_data_layer.cpp:113:39: error: request for member ‘size’ in ‘((caffe::ImageDataLayer<float>*)this)->caffe::ImageDataLayer<float>::<anonymous>.caffe::BasePrefetchingDataLayer<float>::prefetch_’, which is of non-class type ‘caffe::Batch<float> [3]’
   for (int i = 0; i < this->prefetch_.size(); ++i) {
                       ~~~~~~~~~~~~~~~~^~~~
src/caffe/layers/image_data_layer.cpp:114:5: error: base operand of ‘->’ has non-pointer type ‘caffe::Batch<float>’
     this->prefetch_[i]->label_.Reshape(label_shape);
     ^~~~
src/caffe/layers/image_data_layer.cpp: In instantiation of ‘void caffe::ImageDataLayer<Dtype>::DataLayerSetUp(const std::vector<caffe::Blob<Dtype>*>&, const std::vector<caffe::Blob<Dtype>*>&) [with Dtype = double]’:
src/caffe/layers/image_data_layer.cpp:200:1:   required from here
src/caffe/layers/image_data_layer.cpp:101:39: error: request for member ‘size’ in ‘((caffe::ImageDataLayer<double>*)this)->caffe::ImageDataLayer<double>::<anonymous>.caffe::BasePrefetchingDataLayer<double>::prefetch_’, which is of non-class type ‘caffe::Batch<double> [3]’
   for (int i = 0; i < this->prefetch_.size(); ++i) {
                       ~~~~~~~~~~~~~~~~^~~~
src/caffe/layers/image_data_layer.cpp:102:5: error: base operand of ‘->’ has non-pointer type ‘caffe::Batch<double>’
     this->prefetch_[i]->data_.Reshape(top_shape);
     ^~~~
src/caffe/layers/image_data_layer.cpp:113:39: error: request for member ‘size’ in ‘((caffe::ImageDataLayer<double>*)this)->caffe::ImageDataLayer<double>::<anonymous>.caffe::BasePrefetchingDataLayer<double>::prefetch_’, which is of non-class type ‘caffe::Batch<double> [3]’
   for (int i = 0; i < this->prefetch_.size(); ++i) {
                       ~~~~~~~~~~~~~~~~^~~~
src/caffe/layers/image_data_layer.cpp:114:5: error: base operand of ‘->’ has non-pointer type ‘caffe::Batch<double>’
     this->prefetch_[i]->label_.Reshape(label_shape);
     ^~~~
Makefile:575: recipe for target '.build_release/src/caffe/layers/image_data_layer.o' failed

I think it's because my caffe lacks sth.

**Comment by StarIsFalling** [comment]
This problem can be solved from https://blog.csdn.net/u011995719/article/details/79231671

**Comment by chenyiman** [comment]
I have the same problem as you, how to solve it? I have already modify the image_data_layer.cpp/hpp
