### ISSUE TITLE
一张图多人脸处理有思路吗

### ISSUE THREAD

**Issue by Devin147** [tensor-yu/cascaded_mobilenet-v2#3]

**Comment by TingsongYu** [comment]
提的这个需求，正是MTCNN所做的，你可以关注一下MTCNN的思路

**Comment by Devin147** [comment]
那第一级直接回归人脸bbox 不是比关键点更好吗？

**Comment by TingsongYu** [comment]
是的，通常情况下都是先做人脸检测（回归人脸bbox），之后再做人脸关键点检测，但是在特定应用场景下（如，图片中有且仅有一个人脸），就可以省略掉人脸检测过程，直接进行关键点检测。
后期会考虑将人脸检测与人脸关键点检测一起做

**Comment by Devin147** [comment]
问一下作者，这两年有人将MTCNN往上做吗？ 感觉mtcnn有提升空间啊  如果有能推荐一下吗 谢谢

**Comment by Devin147** [comment]
@tensor-yu

**Comment by TingsongYu** [comment]
暂时没看到新论文基于MTCNN往上做
